/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kuver;

import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.NumberFormat;
import java.util.Calendar;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.text.PlainDocument;
import kuver.definitions.Kunde;
import kuver.definitions.User;
import kuver.frame.Register;

/**
 *
 * @author q1
 */
public class View extends javax.swing.JFrame {

    Controller controller;

    /**
     * Creates new form View
     */
    public View(Controller controller) {
        this.controller = controller;
        initComponents();

        // Eigene Einstellungen
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        // Tag
        kuver.tweaks.TextLengthDocFilter filter = new kuver.tweaks.TextLengthDocFilter(2, 0);
        PlainDocument doc = (PlainDocument) neuTagTf.getDocument();
        doc.setDocumentFilter(filter);
        PlainDocument doc2 = (PlainDocument) neuTagTf.getDocument();
        doc2.setDocumentFilter(filter);
        PlainDocument doc3 = (PlainDocument) neuTagTf.getDocument();
        doc3.setDocumentFilter(filter);
        // Jahr
        for (int i = 1930; i < 2010; i++) {
            neuJahrCB.addItem(i);
            sucheJahrCB.addItem(i);
            detailsJahrCB.addItem(i);
        }
        // PLZ
        kuver.tweaks.TextLengthDocFilter filterPLZ = new kuver.tweaks.TextLengthDocFilter(5, 0);
        PlainDocument doc4 = (PlainDocument) neuPlzTf.getDocument();
        doc4.setDocumentFilter(filterPLZ);
        PlainDocument doc5 = (PlainDocument) suchePlzTf.getDocument();
        doc5.setDocumentFilter(filterPLZ);
        PlainDocument doc6 = (PlainDocument) detailsPlzTf.getDocument();
        doc6.setDocumentFilter(filterPLZ);
        // TabPanel
        tabPanel.setEnabledAt(1, false);
        tabPanel.setEnabledAt(2, false);
        tabPanel.setEnabledAt(3, false);

        tabellePanel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabellePanel = new javax.swing.JScrollPane();
        tabelle = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        optNeuBtn = new javax.swing.JButton();
        tabPanel = new javax.swing.JTabbedPane();
        startPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        loginUserTf = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        loginPassPf = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        neuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        neuNameTf = new javax.swing.JTextField();
        neuVornameTf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        neuStrasseTf = new javax.swing.JTextField();
        neuPlzTf = new javax.swing.JTextField();
        neuOrtTf = new javax.swing.JTextField();
        neuAnredeCB = new javax.swing.JComboBox();
        neuMonatCB = new javax.swing.JComboBox();
        neuJahrCB = new javax.swing.JComboBox();
        neuAddBtn = new javax.swing.JButton();
        neuResetBtn = new javax.swing.JButton();
        neueStrNrTf = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        neuTagTf = new javax.swing.JTextField();
        suchePanel = new javax.swing.JPanel();
        sucheSuchenBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sucheNameTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sucheVornameTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sucheMonatCB = new javax.swing.JComboBox();
        sucheJahrCB = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        suchePlzTf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sucheVerlAbTf = new javax.swing.JTextField();
        sucheTagTf = new javax.swing.JTextField();
        sucheStrasseTf = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        sucheStrNrTf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sucheIdTf = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        sucheOrtTf = new javax.swing.JTextField();
        detailsPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        detailsStrasseTf = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        detailsStrNrTf = new javax.swing.JTextField();
        detailsIdTf = new javax.swing.JTextField();
        detailsVornameTf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        detailsNameTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        detailsMonatCB = new javax.swing.JComboBox();
        detailsJahrCB = new javax.swing.JComboBox();
        detailsTagTf = new javax.swing.JTextField();
        sucheVerlAbTf1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        detailsPlzTf = new javax.swing.JTextField();
        detailsSaveBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        detailsAnredeCB = new javax.swing.JComboBox();
        detailsOrtTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        detailsEditBtn = new javax.swing.JButton();
        detailsResetBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        optSuchenBtn = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuBeenden = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KuVer");
        setBackground(java.awt.Color.lightGray);
        setPreferredSize(new java.awt.Dimension(980, 685));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                beendenActionPerformed(evt);
            }
        });

        tabelle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Anrede", "Name", "Vorname", "Geburtsdatum", "Strasse", "Nr", "PLZ", "Ort", "Verlaengerbar", "Vertrag", "Handy", "Registriert seit", "IMEI", "MSISDN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelle.getTableHeader().setReorderingAllowed(false);
        tabelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showKunde(evt);
            }
        });
        tabellePanel.setViewportView(tabelle);
        tabelle.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Neuen Kunden anlegen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        optNeuBtn.setText("Neu");
        optNeuBtn.setEnabled(false);
        optNeuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optNeuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(optNeuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(optNeuBtn)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel21.setText("Willkommen!");

        jLabel29.setText("Melden Sie sich mit Ihrem KuVer-Konto an, um auf das System zuzugreifen.");

        jLabel30.setText("Nutzer");

        loginUserTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserTfActionPerformed(evt);
            }
        });

        jLabel31.setText("Passwort");

        loginPassPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPassPfActionPerformed(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        registerBtn.setText("Registrieren");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(startPanelLayout.createSequentialGroup()
                            .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel31)
                                .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loginUserTf, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(loginPassPf)))))
                .addGap(36, 36, 36)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(registerBtn))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(loginUserTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(loginPassPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBtn)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        tabPanel.addTab("Start", startPanel);

        jLabel1.setText("Name");

        jLabel2.setText("Vorname");

        jLabel3.setText("Anrede");

        neuNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuNameTfActionPerformed(evt);
            }
        });

        jLabel4.setText("Geburtsdatum");

        jLabel5.setText("Strasse/Nr");

        jLabel6.setText("PLZ/Ort");

        jLabel7.setText("/");

        neuPlzTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuPlzTfActionPerformed(evt);
            }
        });

        neuAnredeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Herr", "Frau" }));
        neuAnredeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuAnredeCBActionPerformed(evt);
            }
        });

        neuMonatCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));
        neuMonatCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setTag(evt);
            }
        });

        neuJahrCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        neuAddBtn.setText("Hinzufuegen");
        neuAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuAddBtnActionPerformed(evt);
            }
        });

        neuResetBtn.setText("Reset");

        neueStrNrTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neueStrNrTfActionPerformed(evt);
            }
        });

        jLabel22.setText("/");

        neuTagTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuTagTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout neuPanelLayout = new javax.swing.GroupLayout(neuPanel);
        neuPanel.setLayout(neuPanelLayout);
        neuPanelLayout.setHorizontalGroup(
            neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(neuPanelLayout.createSequentialGroup()
                .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, neuPanelLayout.createSequentialGroup()
                        .addContainerGap(770, Short.MAX_VALUE)
                        .addComponent(neuResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(neuAddBtn))
                    .addGroup(neuPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(neuAnredeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(neuPanelLayout.createSequentialGroup()
                                .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(neuPanelLayout.createSequentialGroup()
                                        .addComponent(neuStrasseTf, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(neueStrNrTf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(neuPanelLayout.createSequentialGroup()
                                        .addComponent(neuTagTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(neuMonatCB, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(neuJahrCB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(neuNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(neuPanelLayout.createSequentialGroup()
                                        .addComponent(neuPlzTf, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(neuOrtTf)))
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neuVornameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        neuPanelLayout.setVerticalGroup(
            neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, neuPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(neuAnredeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(neuNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(neuVornameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(neuMonatCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neuJahrCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neuTagTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(neuStrasseTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neueStrNrTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(neuPlzTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neuOrtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(neuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neuAddBtn)
                    .addComponent(neuResetBtn)))
        );

        tabPanel.addTab("Neu", neuPanel);

        sucheSuchenBtn.setText("Suchen");
        sucheSuchenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucheSuchenBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Name");

        jLabel9.setText("Vorname");

        sucheVornameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucheVornameTfActionPerformed(evt);
            }
        });

        jLabel10.setText("Geburtsdatum");

        sucheMonatCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));
        sucheMonatCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setTag(evt);
            }
        });
        sucheMonatCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucheMonatCBActionPerformed(evt);
            }
        });

        sucheJahrCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        jLabel11.setText("PLZ/Ort");

        jLabel12.setText("Verlaengerbar ab");

        jLabel23.setText("Strasse/Nr");

        jLabel24.setText("/");

        jLabel17.setText("ID");

        sucheIdTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucheIdTfActionPerformed(evt);
            }
        });

        jLabel28.setText("/");

        javax.swing.GroupLayout suchePanelLayout = new javax.swing.GroupLayout(suchePanel);
        suchePanel.setLayout(suchePanelLayout);
        suchePanelLayout.setHorizontalGroup(
            suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suchePanelLayout.createSequentialGroup()
                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, suchePanelLayout.createSequentialGroup()
                        .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suchePanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel17))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suchePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)))
                        .addGap(15, 15, 15)
                        .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sucheIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(suchePanelLayout.createSequentialGroup()
                                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, suchePanelLayout.createSequentialGroup()
                                        .addComponent(sucheTagTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sucheMonatCB, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sucheJahrCB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(suchePanelLayout.createSequentialGroup()
                                        .addComponent(sucheStrasseTf, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sucheStrNrTf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sucheVerlAbTf)
                                    .addComponent(sucheNameTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, suchePanelLayout.createSequentialGroup()
                                        .addComponent(suchePlzTf, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sucheOrtTf)))
                                .addGap(59, 59, 59)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sucheVornameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(suchePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sucheSuchenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        suchePanelLayout.setVerticalGroup(
            suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suchePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(sucheIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sucheNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(sucheVornameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sucheMonatCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sucheJahrCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sucheTagTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sucheStrasseTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(sucheStrNrTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(suchePlzTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(sucheOrtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(suchePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sucheVerlAbTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(sucheSuchenBtn)
                .addContainerGap())
        );

        tabPanel.addTab("Suche", suchePanel);

        jLabel25.setText("Strasse/Nr");

        detailsStrasseTf.setEditable(false);

        jLabel26.setText("/");

        detailsStrNrTf.setEditable(false);

        detailsIdTf.setEditable(false);

        detailsVornameTf.setEditable(false);
        detailsVornameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsVornameTfActionPerformed(evt);
            }
        });

        jLabel14.setText("Geburtsdatum");

        detailsNameTf.setEditable(false);

        jLabel15.setText("Vorname");

        jLabel16.setText("PLZ/Ort");

        detailsMonatCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember" }));
        detailsMonatCB.setEnabled(false);
        detailsMonatCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                detailsMonatCBsetTag(evt);
            }
        });
        detailsMonatCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsMonatCBActionPerformed(evt);
            }
        });

        detailsJahrCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        detailsJahrCB.setEnabled(false);

        detailsTagTf.setEditable(false);

        sucheVerlAbTf1.setEditable(false);

        jLabel18.setText("Verlaengerbar ab");

        jLabel19.setText("Name");

        detailsPlzTf.setEditable(false);

        detailsSaveBtn.setText("Speichern");
        detailsSaveBtn.setEnabled(false);
        detailsSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsSaveBtnActionPerformed(evt);
            }
        });

        jLabel20.setText("ID");

        jLabel27.setText("Anrede");

        detailsAnredeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Herr", "Frau" }));
        detailsAnredeCB.setEnabled(false);

        jLabel13.setText("/");

        detailsEditBtn.setText("Bearbeiten");
        detailsEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsEditBtnActionPerformed(evt);
            }
        });

        detailsResetBtn.setText("Reset");
        detailsResetBtn.setEnabled(false);
        detailsResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel27))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)))
                        .addGap(15, 15, 15)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsPanelLayout.createSequentialGroup()
                                        .addComponent(detailsTagTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(detailsMonatCB, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(detailsJahrCB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sucheVerlAbTf1)
                                    .addComponent(detailsNameTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detailsPanelLayout.createSequentialGroup()
                                        .addComponent(detailsStrasseTf, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(detailsStrNrTf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(detailsPanelLayout.createSequentialGroup()
                                        .addComponent(detailsPlzTf, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(detailsOrtTf)))
                                .addGap(59, 59, 59)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detailsVornameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE))
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(detailsIdTf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detailsAnredeCB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(detailsResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(detailsEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailsSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPanelLayout.createSequentialGroup()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(detailsIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(detailsResetBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(detailsAnredeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(detailsNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(detailsVornameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(detailsMonatCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detailsJahrCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detailsTagTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detailsStrasseTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(detailsStrNrTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(detailsPlzTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(detailsOrtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(sucheVerlAbTf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detailsSaveBtn)
                            .addComponent(detailsEditBtn))
                        .addContainerGap())))
        );

        tabPanel.addTab("Details", detailsPanel);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kunden suchen", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        optSuchenBtn.setText("Suchen");
        optSuchenBtn.setEnabled(false);
        optSuchenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSuchenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(optSuchenBtn)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(optSuchenBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(new java.awt.Color(149, 147, 137));

        jMenu3.setText("Optionen");

        menuBeenden.setText("Beenden");
        menuBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBeendenActionPerformed(evt);
            }
        });
        jMenu3.add(menuBeenden);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Hilfe");

        jMenuItem2.setText("Anleitung");
        jMenu4.add(jMenuItem2);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabellePanel)
            .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabellePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void neuNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neuNameTfActionPerformed

    private void neuPlzTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuPlzTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neuPlzTfActionPerformed

    private void neuAnredeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuAnredeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neuAnredeCBActionPerformed

    private void sucheVornameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheVornameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucheVornameTfActionPerformed

    private void optSuchenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSuchenBtnActionPerformed
        tabPanel.setEnabledAt(2, true);
        tabPanel.setSelectedIndex(2);
        // Test: generiere Kunden in Tabelle
        controller.test(tabelle);
    }//GEN-LAST:event_optSuchenBtnActionPerformed

    private void neuAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuAddBtnActionPerformed
        // Check input
        String error = checkInput();
        if (error != null) {
            JOptionPane.showMessageDialog(tabPanel,
                    "Fehler bei der Eingabe: " + error,
                    "Falsche Eingabe",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Add
        controller.addKunde(tabelle, getNeuKunde());

    }//GEN-LAST:event_neuAddBtnActionPerformed

    private void optNeuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optNeuBtnActionPerformed
        tabPanel.setEnabledAt(1, true);
        tabPanel.setSelectedIndex(1);
//        if(tab.getTabCount()>2)
//        tab.remove(neuPanel);
//        else
//        tab.addTab("Neu", neuPanel);
    }//GEN-LAST:event_optNeuBtnActionPerformed

    private void showKunde(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showKunde
        tabPanel.setEnabledAt(3, true);
        // Switch to details tab
        if (tabPanel.getSelectedIndex() != 3) {
            tabPanel.setSelectedIndex(3);
        }

        // Check if EditMode
        if (controller.isEditMode()) {
            return;
        }

        // Get clicked Kunde
        int row = tabelle.rowAtPoint(evt.getPoint());
        int col = tabelle.columnAtPoint(evt.getPoint());
        Kunde kunde = new Kunde();
        kunde.setId((Integer) tabelle.getModel().getValueAt(row, 0));
        kunde.setAnrede((String) tabelle.getModel().getValueAt(row, 1));
        kunde.setName((String) tabelle.getModel().getValueAt(row, 2));
        kunde.setVorname((String) tabelle.getModel().getValueAt(row, 3));
        // Bday
        kunde.setGebDat(stringToCalendar((String) tabelle.getModel().getValueAt(row, 4)));
        kunde.setStrasse((String) tabelle.getModel().getValueAt(row, 5));
        kunde.setStrNr((Integer) tabelle.getModel().getValueAt(row, 6));
        kunde.setPlz((String) tabelle.getModel().getValueAt(row, 7));
        kunde.setOrt((String) tabelle.getModel().getValueAt(row, 8));
        // todo: etc..
        controller.setCurKunde(kunde);

        // Details
        fillDetails(kunde);
    }//GEN-LAST:event_showKunde

    private void menuBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBeendenActionPerformed
        beendenActionPerformed(null);
    }//GEN-LAST:event_menuBeendenActionPerformed

    private void beendenActionPerformed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_beendenActionPerformed
        // TODO add your handling code here:

        if (!controller.isEditMode()) {
            System.exit(0);
        }

        JOptionPane.showMessageDialog(tabPanel,
                "Sie haben noch ungespeicherte Daten.\nSpeichern oder Verwerfen sie diese zuerst.",
                "Achtung! Geaenderte Daten!",
                JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_beendenActionPerformed

    private void sucheMonatCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheMonatCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucheMonatCBActionPerformed

    private void setTag(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setTag
        // TODO add your handling code here:
    }//GEN-LAST:event_setTag

    private void neueStrNrTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neueStrNrTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neueStrNrTfActionPerformed

    private void detailsVornameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsVornameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsVornameTfActionPerformed

    private void detailsMonatCBsetTag(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_detailsMonatCBsetTag
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsMonatCBsetTag

    private void detailsMonatCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsMonatCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsMonatCBActionPerformed

    private void sucheIdTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheIdTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sucheIdTfActionPerformed

    private void detailsSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsSaveBtnActionPerformed
        // Check input

        // Dialog
        final JOptionPane optionPane = new JOptionPane(
                "Wollen sie Aenderungen uebernehmen?\n",
                JOptionPane.QUESTION_MESSAGE,
                JOptionPane.YES_NO_CANCEL_OPTION);

        final JDialog dialog = new JDialog(this,
                "Aenderungen speichern",
                true);
        dialog.setContentPane(optionPane);
//        dialog.setDefaultCloseOperation(
//                JDialog.DO_NOTHING_ON_CLOSE);
//        dialog.addWindowListener(new WindowAdapter() {
//            public void windowClosing(WindowEvent we) {
//                setLabel("Thwarted user attempt to close window.");
//            }
//        });
        optionPane.addPropertyChangeListener(
                new PropertyChangeListener() {
                    public void propertyChange(PropertyChangeEvent e) {
                        String prop = e.getPropertyName();

                        if (dialog.isVisible()
                                && (e.getSource() == optionPane)
                                && (prop.equals(JOptionPane.VALUE_PROPERTY))) {
                            //If you were going to check something
                            //before closing the window, you'd do
                            //it here.
                            dialog.setVisible(false);
                        }
                    }
                });
        dialog.pack();
        dialog.setLocationRelativeTo(detailsPanel);
        dialog.setVisible(true);


        int value = ((Integer) optionPane.getValue()).intValue();
        if (value == JOptionPane.YES_OPTION) { // Save
            controller.updateKunde(getDetailsKunde());
        } else if (value == JOptionPane.NO_OPTION) {
            detailsReset();
        } else if (value == JOptionPane.CANCEL_OPTION) {
            return;
        }

        // Exit EditMode
        disableEditMode();

    }//GEN-LAST:event_detailsSaveBtnActionPerformed

    private void detailsEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsEditBtnActionPerformed
        // Enable EditMode
        enableEditMode();

    }//GEN-LAST:event_detailsEditBtnActionPerformed

    private void detailsResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsResetBtnActionPerformed
        // Reset changes
        detailsReset();
    }//GEN-LAST:event_detailsResetBtnActionPerformed

    private void loginPassPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPassPfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPassPfActionPerformed

    private void loginUserTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserTfActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // Check login input
//        if (loginUserTf.getText().length() < 3) {
//            JOptionPane.showMessageDialog(tabPanel,
//                    "Fehler: Nutzer muss aus mehr als 2 Buchstaben bestehen!",
//                    "Ungueltiger Nutzer",
//                    JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        if (loginPassPf.getPassword().length < 7) {
//            JOptionPane.showMessageDialog(tabPanel,
//                    "Fehler: Passwort muss aus mehr als 6 Buchstaben bestehen!",
//                    "Ungueltiges Passwort",
//                    JOptionPane.WARNING_MESSAGE);
//            return;
//        }
        User user = new User(loginUserTf.getText(), String.valueOf(loginPassPf.getPassword()));

        // Lookup in db
        if (controller.login(user)) {
            userVerified();
        } else {
            JOptionPane.showMessageDialog(tabPanel,
                    "Ihre Anmeldung schlug fehl. Bitte ueberpruefen Sie Ihre Eingabe.\nWenn Sie noch kein KuVer-Konto besitzen, registrieren Sie sich bitte.",
                    "Login fehlgeschlagen",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        Register register = new Register(controller, this, true);
        register.pack();
        register.setLocationRelativeTo(detailsPanel);
        register.setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void neuTagTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuTagTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neuTagTfActionPerformed

    private void sucheSuchenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucheSuchenBtnActionPerformed
        // suchen
        controller.sucheKunde(tabelle,getSucheKunde());
    }//GEN-LAST:event_sucheSuchenBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View(new Controller()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox detailsAnredeCB;
    private javax.swing.JButton detailsEditBtn;
    private javax.swing.JTextField detailsIdTf;
    private javax.swing.JComboBox detailsJahrCB;
    private javax.swing.JComboBox detailsMonatCB;
    private javax.swing.JTextField detailsNameTf;
    private javax.swing.JTextField detailsOrtTf;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JTextField detailsPlzTf;
    private javax.swing.JButton detailsResetBtn;
    private javax.swing.JButton detailsSaveBtn;
    private javax.swing.JTextField detailsStrNrTf;
    private javax.swing.JTextField detailsStrasseTf;
    private javax.swing.JTextField detailsTagTf;
    private javax.swing.JTextField detailsVornameTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField loginPassPf;
    private javax.swing.JTextField loginUserTf;
    private javax.swing.JMenuItem menuBeenden;
    private javax.swing.JButton neuAddBtn;
    private javax.swing.JComboBox neuAnredeCB;
    private javax.swing.JComboBox neuJahrCB;
    private javax.swing.JComboBox neuMonatCB;
    private javax.swing.JTextField neuNameTf;
    private javax.swing.JTextField neuOrtTf;
    private javax.swing.JPanel neuPanel;
    private javax.swing.JTextField neuPlzTf;
    private javax.swing.JButton neuResetBtn;
    private javax.swing.JTextField neuStrasseTf;
    private javax.swing.JTextField neuTagTf;
    private javax.swing.JTextField neuVornameTf;
    private javax.swing.JTextField neueStrNrTf;
    private javax.swing.JButton optNeuBtn;
    private javax.swing.JButton optSuchenBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel startPanel;
    private javax.swing.JTextField sucheIdTf;
    private javax.swing.JComboBox sucheJahrCB;
    private javax.swing.JComboBox sucheMonatCB;
    private javax.swing.JTextField sucheNameTf;
    private javax.swing.JTextField sucheOrtTf;
    private javax.swing.JPanel suchePanel;
    private javax.swing.JTextField suchePlzTf;
    private javax.swing.JTextField sucheStrNrTf;
    private javax.swing.JTextField sucheStrasseTf;
    private javax.swing.JButton sucheSuchenBtn;
    private javax.swing.JTextField sucheTagTf;
    private javax.swing.JTextField sucheVerlAbTf;
    private javax.swing.JTextField sucheVerlAbTf1;
    private javax.swing.JTextField sucheVornameTf;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tabelle;
    private javax.swing.JScrollPane tabellePanel;
    // End of variables declaration//GEN-END:variables

    private void fillDetails(Kunde kunde) {
        detailsIdTf.setText("" + kunde.getId());
        detailsAnredeCB.setSelectedItem(kunde.getAnrede());
        detailsNameTf.setText(kunde.getName());
        detailsVornameTf.setText(kunde.getVorname());
        detailsStrasseTf.setText(kunde.getStrasse());
        // Bday
        detailsTagTf.setText(kunde.getGebDat().get(Calendar.DAY_OF_MONTH) + "");
        detailsMonatCB.setSelectedIndex(kunde.getGebDat().get(Calendar.MONTH) - 1);
        detailsJahrCB.setSelectedItem(kunde.getGebDat().get(Calendar.YEAR));
        detailsStrNrTf.setText("" + kunde.getStrNr());
        detailsPlzTf.setText(kunde.getPlz());
        detailsOrtTf.setText(kunde.getOrt());

    }

    /**
     * Check input
     *
     * @return
     */
    private String checkInput() {
        String error = null;
        // Anrede
        if (neuAnredeCB.getSelectedIndex() == 0) {
            error = "'Anrede' ist leer! ";
            return error;
        }
        System.out.println("name: " + neuAnredeCB.getSelectedItem().toString());
        // Name
        if (neuNameTf.getText().isEmpty()) {
            error = "'Name' ist leer! ";
            return error;
        }
        System.out.println("name: " + neuNameTf.getText());
        if (!(neuNameTf.getText()).matches("[a-zA-Z]+")) {
            error = "'Name' darf keine Sonderzeichen oder Zahlen enthalten! ";
            return error;
        }
        // Vorname
        if (neuVornameTf.getText().isEmpty()) {
            error = "'Vorname' ist leer! ";
            return error;
        }
        System.out.println("name: " + neuVornameTf.getText());
        if (!(neuVornameTf.getText()).matches("[a-zA-Z]+")) {
            error = "'Vorname' darf keine Sonderzeichen oder Zahlen enthalten! ";
            return error;
        }
        // Strasse
        if (neuStrasseTf.getText().isEmpty()) {
            error = "'Strasse' ist leer! ";
            return error;
        }
        System.out.println("Strasse: " + neuStrasseTf.getText());
        if (!(neuStrasseTf.getText()).matches("^[A-Za-z-]*[a-z]+$")) {
            error = "'Strasse' darf keine Zahlen oder Sonderzeichen enthalten! Bindestriche koennen nur innerhalb eines Wortes auftauchen.";
            return error;
        }
        return error;
    }

    /**
     * Get 'Neuer' Kunde
     *
     * @return Kunde
     *
     */
    private Kunde getNeuKunde() {
        Kunde kunde = new kuver.definitions.Kunde();
        kunde.setAnrede(neuAnredeCB.getSelectedItem().toString());
        kunde.setName(neuNameTf.getText());
        kunde.setVorname(neuVornameTf.getText());
        kunde.setStrasse(neuStrasseTf.getText());
        kunde.setPlz(neuPlzTf.getText());
        kunde.setOrt(neuOrtTf.getText());

        return kunde;
    }

    private Kunde getDetailsKunde() {
        Kunde kunde = new kuver.definitions.Kunde();
        kunde.setName(detailsNameTf.getText());
        kunde.setVorname(detailsVornameTf.getText());
        kunde.setStrasse(detailsStrasseTf.getText());
        kunde.setPlz(detailsPlzTf.getText());
        kunde.setOrt(detailsOrtTf.getText());

        return kunde;
    }

    private Kunde getSucheKunde() {
        Kunde kunde = new kuver.definitions.Kunde();
        if(!sucheIdTf.getText().isEmpty())
            kunde.setId(Integer.parseInt(sucheIdTf.getText()));
        kunde.setName(sucheNameTf.getText());
        kunde.setVorname(sucheVornameTf.getText());
        kunde.setStrasse(sucheStrasseTf.getText());
        // Bday
        int tag = 0;
        int monat = 0;
        int jahr = 0;
        if (!sucheTagTf.getText().isEmpty()) {
            tag = Integer.parseInt(sucheTagTf.getText());
        }
        if (sucheMonatCB.getSelectedIndex() != 0) {
            monat = sucheMonatCB.getSelectedIndex() - 1;
        }
        if (sucheJahrCB.getSelectedIndex() != 0) {
            jahr = Integer.parseInt(sucheJahrCB.getSelectedItem().toString());
        }
        if (tag == 0 || jahr == 0 || monat == 0) {// skip bday
        } 
        else {
            Calendar dat = Calendar.getInstance();
            dat.set(jahr, monat, tag);
            kunde.setGebDat(dat);
        }
        kunde.setPlz(suchePlzTf.getText());
        kunde.setOrt(sucheOrtTf.getText());

        return kunde;
    }

    private void detailsReset() {
        fillDetails(controller.getCurKunde());
    }

    private void disableEditMode() {
        controller.setEditMode(false);
        detailsPanel.setBackground(suchePanel.getBackground());
        detailsEditBtn.setEnabled(true);
        detailsSaveBtn.setEnabled(false);
        detailsResetBtn.setEnabled(false);

        // Disable edit
        detailsAnredeCB.setEnabled(false);
        detailsNameTf.setEditable(false);
        detailsTagTf.setEditable(false);
        detailsMonatCB.setEnabled(false);
        detailsJahrCB.setEnabled(false);
        detailsStrasseTf.setEditable(false);
        detailsStrNrTf.setEditable(false);
        detailsPlzTf.setEditable(false);
        detailsOrtTf.setEditable(false);
        // todo: rest.. 
    }

    private void enableEditMode() {
        controller.setEditMode(true);
        detailsPanel.setBackground(Color.lightGray);
        detailsEditBtn.setEnabled(false);
        detailsSaveBtn.setEnabled(true);
        detailsResetBtn.setEnabled(true);
        // Enable Edit
        detailsAnredeCB.setEnabled(true);
        detailsNameTf.setEditable(true);
        detailsTagTf.setEditable(true);
        detailsMonatCB.setEnabled(true);
        detailsJahrCB.setEnabled(true);
        detailsStrasseTf.setEditable(true);
        detailsStrNrTf.setEditable(true);
        detailsPlzTf.setEditable(true);
        detailsOrtTf.setEditable(true);
        // todo: rest.. 
    }

    private Calendar stringToCalendar(String str) {
        String[] split = str.split("\\.");
        System.out.println("str: " + str + " size: " + split.length);
        if (split.length != 3) {
            throw new IllegalArgumentException("String '" + str + "' not in correct format");
        }
        Calendar cal = Calendar.getInstance();
        cal.set(Integer.parseInt(split[2]), Integer.parseInt(split[1]), Integer.parseInt(split[0]));

        return cal;
    }

    private void userVerified() {
        // disable login
        loginBtn.setEnabled(false);
        loginUserTf.setEnabled(false);
        loginPassPf.setEnabled(false);
        optNeuBtn.setEnabled(true);
        optSuchenBtn.setEnabled(true);
        tabellePanel.setVisible(true);

        // msg
        JOptionPane.showMessageDialog(tabPanel,
                "Sie haben sich erfolgreich angemeldet!",
                "Login erfolgreich",
                JOptionPane.INFORMATION_MESSAGE);
    }
}
